### ISSUE TITLE
Some dismatch in the training process

### ISSUE THREAD

**Issue by CCCYCLONE** [vision4robotics/PRL-Track#1]
I met a problem in the training process.Can you give me some guidances?Thank you very much!
File "/PRL-Track-main/./pysot/models/model_builder.py", line 87, in getcentercuda
    anchor[:, :, 0] = x - w / 2
RuntimeError: The expanded size of the tensor (64) must match the existing size (128) at non-singleton dimension 0.  Target sizes: [64, 121].  Tensor sizes: [128, 121]

**Comment by Lei00764** [comment]
Thank you for reaching out, and I appreciate your patience.

The error you're encountering, "RuntimeError: The expanded size of the tensor (64) must match the existing size (128) at non-singleton dimension 0," is because the default GPU number is 2.

If you're using a single GPU or you have more than 2 GPUs, you'll need to adjust the GPU number in the configuration file. Please modify the setting in `./experiments/config.yaml.`
