### ISSUE TITLE
循环嵌套导入包

### ISSUE THREAD

**Issue by Streaming-Understanding** [vision4robotics/PRL-Track#2]
<img width="542" alt="bfe7d41ba1ebc7c4ef5f50d044faf72" src="https://github.com/user-attachments/assets/26d3d960-b154-48d7-bcae-ab7fe422564d" />
how to fix this problem

**Comment by Lei00764** [comment]
Thank you very much for your attention and support for our work.

Regarding the issue you mentioned, I just conducted a test in the local environment and confirmed that running `python tools/eval.py` works directly without import errors. This indicates that the problem may not be caused by code nesting.

I suggest you execute the command `python setup.py build_ext --inplace` in the project's root directory first to compile the Cython code in the project, and then try running the evaluation script. This step is essential as the project includes Cython components that require prior compilation.

Thank you again for your attention! If you encounter any issues during the process, please feel free to contact me.
